#!/bin/bash
# crear_carpetaArchivos.sh
#Crear carpeta
mkdir nueva_carpeta
#Creación de los dos archivos con vectores de 5 enteros
echo "1 2 3 4 5" > nueva_carpeta/archivo01.txt
echo "6 7 8 9 10" > nueva_carpeta/archivo02.txt
